name: assignment_pepper
description: assignment for pepper

publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  http: ^0.13.5
  dio: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  assets:
    - assets/mocks/mock_operations.json

  uses-material-design: true
